# Generated by Django 3.0.3 on 2020-04-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('men_url', models.CharField(max_length=200, verbose_name='链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(1, '启用'), (2, '未启用')], default=1, verbose_name='状态')),
                ('order_no', models.IntegerField(default=1, verbose_name='排序号')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Page', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name_plural': '部门信息',
                'db_table': 'page',
            },
        ),
    ]
