# Generated by Django 3.0.3 on 2020-04-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='men_url',
        ),
        migrations.AddField(
            model_name='page',
            name='menu_url',
            field=models.CharField(default='test', help_text='链接', max_length=200, verbose_name='链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_name',
            field=models.CharField(help_text='菜单名称', max_length=50, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order_no',
            field=models.IntegerField(default=1, help_text='排序号', verbose_name='排序号'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='上级菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Page', verbose_name='上级菜单'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (2, '未启用')], default=1, help_text='状态', verbose_name='状态'),
        ),
    ]
