# Generated by Django 3.0.3 on 2020-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200403_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_code',
            field=models.CharField(default='home', help_text='菜单代码', max_length=20, verbose_name='菜单代码'),
            preserve_default=False,
        ),
    ]
