# Generated by Django 3.0.3 on 2020-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_menu_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_icon',
            field=models.CharField(blank=True, help_text='菜单代码', max_length=100, null=True, verbose_name='菜单图标'),
        ),
    ]
