# Generated by Django 3.0.3 on 2020-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu_icon',
            field=models.CharField(blank=True, help_text='菜单图标', max_length=100, null=True, verbose_name='菜单图标'),
        ),
    ]
