# Generated by Django 3.0.3 on 2020-04-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='角色名称', max_length=50, verbose_name='角色名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RolesButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='button.Membership', verbose_name='页面按钮')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Role', verbose_name='角色')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='button',
            field=models.ManyToManyField(through='role.RolesButton', to='button.Membership'),
        ),
    ]
