# Generated by Django 3.0.3 on 2020-04-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.IntegerField(choices=[(1, '启用'), (2, '未启用')], default=1, help_text='状态', verbose_name='状态'),
        ),
    ]
