# Generated by Django 3.0.3 on 2020-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_code', models.CharField(max_length=10, unique=True, verbose_name='柜员号')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
