# Generated by Django 3.0.3 on 2020-03-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
