# Generated by Django 3.0.3 on 2020-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='button_code',
            field=models.CharField(default='del', help_text='按钮代码', max_length=50, verbose_name='按钮代码'),
            preserve_default=False,
        ),
    ]
