# Generated by Django 3.0.3 on 2020-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_button_button_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='button_icon',
            field=models.CharField(blank=True, help_text='按钮图标', max_length=100, null=True, verbose_name='按钮图标'),
        ),
    ]
