# Generated by Django 3.0.3 on 2020-03-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_parent_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部门代码'),
        ),
    ]
